[package]
name = "proof-of-attendance"
version = "1.0.0"
authors = []

[addresses]
MyModule="0x4b8c1d5c71a95ab878349d36395e27a1cb5680e87322c35378ab6d7334dc3bdc"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
